name: catalogo_front
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6'

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^2.0.0
  http: ^1.2.0

  cupertino_icons: ^1.0.2
  flutter_camera_qrcode_scanner: ^2.0.0
  webview_flutter: ^4.7.0
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
