name: catalogo_front
description: "Sistema de Catalogo"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^2.0.0
  http: ^1.2.0

  cupertino_icons: ^1.0.2
  flutter_camera_qrcode_scanner: ^2.0.0
  webview_flutter: ^4.7.0
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  google_fonts: 6.1.0
  dio: ^5.4.1
  beamer: ^1.6.0
  get_it: ^7.6.7
  either_dart: ^1.0.0
  reactive_forms: ^16.1.1
  dio_http_formatter: ^3.2.1
  dio_cache_interceptor: ^3.5.0
  freezed_annotation: ^2.4.1
  icons_plus: ^5.0.0

dev_dependencies:
  bloc_test: ^9.1.6
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

